- name: Starting services in Translator Server
  hosts: STN-Trans
  tasks:
        - name: Starting Service
          win_service:
                      name: "{{ item }}"
                      state: started
          with_items:
                      - ATFTPD
                      - AcresTimeProtocol
                      - AbsTranslator
