---
- name: Starting ABS installation
  hosts: STN-Trans
  vars:
        featurename : "{{ featurename }}"
  tasks:
        - name: Adding feature MSMQ
          win_feature:
                      name: "{{ featurename }}"
                      state: present

  tasks:
        - name: IPS Install - Proceed with manual steps ahead
          debug:
            msg: "Please proceed with the IPS steps manually by selecting following services in Translator Server : 27-ABS Translator Installer"
