---
- name: Starting ABS installation
  hosts: STN-Trans
  vars:
        servicename : "{{ servicename }}"
  tasks:
        - name: Adding feature MSMQ
          win_feature:
                      name: "{{ servicename }}"
                      state: present
